### PR TITLE
Griptape Cloud API Reference

### PR DESCRIPTION
**Pull request by zachgiordano**
* Added Griptape Cloud API Reference via Swagger UI plugin
* API definition is included for now, but will be hosted elsewhere
* Inspired by: https://github.com/byrnereese/mkdocs-swagger-ui

----
:books: Documentation preview :books:: https://griptape--157.org.readthedocs.build/

### CODE REVIEW

**Comment by collindutter** [comment]
Fixed preview link, looks like there is an error loading the swagger

**Comment by zachgiordano** [comment]
Note: I Still need to fix where the spec_url is retrieved for Swagger

**Comment by zachgiordano** [comment]
> Fixed preview link, looks like there is an error loading the swagger

@collindutter updated this to pull the hosted openapi spec. Should work now!

**Comment by collindutter** [comment]
That it does! Can we tweak some of the colors for better contrast against the background?

**Comment by zachgiordano** [comment]
@collindutter How's it looking now? Made it more dark-mode like. Darker backgrounds, lighter text. You may have to empty cache and reload to see the changes on the preview site.

**Comment by collindutter** [comment]
@zachgiordano the paths look much better, but the schemas are still kind of hard to read. Tweaking it to match the servers section improves it quite a bit:
image
image

Also something doesn't quite look right here. I think needs a little padding and removal of the extras lines.
image

**Comment by zachgiordano** [comment]
@collindutter good call, and thanks for the reference pics! Hopefully the new commit cleans it up

**Comment by collindutter** [comment]
Looks good. Last nit pick, the hover color on schemas feels a little off. Maybe disable since the other elements don't really have hover states?
image

Also, should the Griptape Cloud nav link go closer to the Griptape Reference Guide since they're both reference material?

**Comment by zachgiordano** [comment]
@collindutter Agreed, it looks better without the hover. Also moved the nav link

**Comment by collindutter** [comment]
While we're in here maybe we should shorten up the nav link names since it's getting lengthy. Maybe remove "Griptape" from each one?

**Review by vachillo — DISMISSED** [review]

**Comment by zachgiordano** [comment]
@collindutter Yeah I agree. I shortened the nav link names with the latest commit

**Pull request closed without merging**
